name: Android ARMv7 Clean Build

on:
  workflow_dispatch:

env:
  RUST_VERSION: "1.75"
  CARGO_NDK_VERSION: "3.1.2"
  ANDROID_FLUTTER_VERSION: "3.24.5"
  NDK_VERSION: "r27c"
  VCPKG_COMMIT_ID: "120deac3062162151622ca4860575a33844ba10b"
  VERSION: "1.4.6"
  VCPKG_BINARY_SOURCES: "clear"

jobs:
  generate-bridge:
    uses: ./.github/workflows/bridge.yml

  build-android-armv7:
    needs: [generate-bridge]
    runs-on: ubuntu-24.04
    timeout-minutes: 180

    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: false
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: false

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - name: Fix submodules
        run: |
          git submodule sync
          git submodule update --init --recursive --force

